apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-payment-credit
  namespace: nautible-app-ms
  labels:
    app.kubernetes.io/name: nautible-app-ms-payment-credit
    app.kubernetes.io/instance: nautible-app-ms-payment-credit
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nautible-app-ms-payment-credit
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nautible-app-ms-payment-credit
        app.kubernetes.io/instance: nautible-app-ms-payment-credit
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: app
        app.kubernetes.io/part-of: nautible
        app.kubernetes.io/managed-by: manual
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nautible-app-ms-payment-credit"
        dapr.io/app-port: "8080"
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }' # https://github.com/dapr/dapr/issues/2657
    spec:
      containers:
        - name: nautible-app-ms-payment-credit
          image: public.ecr.aws/nautible/nautible-app-ms-payment-credit:cd552ab4a1e5966cdd9024a2151ce89308b7b462
          ports:
            - containerPort: 8080
            - containerPort: 9000
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
            failureThreshold: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
            failureThreshold: 10
            periodSeconds: 30
