apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-payment-convenience
  namespace: nautible-app
  labels:
    app.kubernetes.io/name: nautible-app-payment-convenience
    app.kubernetes.io/instance: nautible-app-payment-convenience
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nautible-app-payment-convenience
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nautible-app-payment-convenience
        app.kubernetes.io/instance: nautible-app-payment-convenience
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: app
        app.kubernetes.io/part-of: nautible
        app.kubernetes.io/managed-by: manual
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nautible-app-payment-convenience"
        dapr.io/app-port: "8080"
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }' # https://github.com/dapr/dapr/issues/2657
    spec:
      containers:
        - name: nautible-app-payment-convenience
          image: public.ecr.aws/nautible/nautible-app-payment-convenience:21a1f1f0f57da8cb20db2eface1d2edc7abae1c9
          ports:
            - containerPort: 8080
            - containerPort: 9000
          livenessProbe:
            httpGet:
              port: 8080
              path: /health/live
            failureThreshold: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              port: 8080
              path: /health/ready
            failureThreshold: 10
            periodSeconds: 30
