apiVersion: v1
kind: Service
metadata:
  name: nautible-app-ms-payment-cash
  namespace: nautible-app-ms
  labels:
    app.kubernetes.io/name: nautible-app-ms-payment-cash
    app.kubernetes.io/instance: nautible-app-ms-payment-cash
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  selector:
    app.kubernetes.io/instance: nautible-app-ms-payment-cash
    app.kubernetes.io/component: app
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 9000
      targetPort: 9000
