---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-payment
  namespace: nautible-app-ms
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nautible-app-ms-payment
        image: nautible-app-ms-payment
        env:
        - name: DB_CONNECTION_STRING
          value: mongodb://${DB_USER}:${DB_PW}@payment-mongodb:27017/Payment?authSource=admin
        - name: DB_USER
          value: root
        - name: DB_PW
          value: password
