---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-payment-credit
  namespace: nautible-app-ms
spec:
  replicas: 1
  template:
    spec:
      initContainers:
      - name: wait-payment
        image: busybox
        command: ['sh', '-c', "until nslookup nautible-app-ms-payment.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for payment; sleep 2; done"]
      containers:
      - name: nautible-app-ms-payment-credit
        image: nautible-app-ms-payment-credit
        env:
        - name: DB_CONNECTION_STRING
          value: mongodb://${DB_USER}:${DB_PW}@payment-mongodb:27017/Payment?authSource=admin
        - name: DB_USER
          value: root
        - name: DB_PW
          value: password
