---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-payment-cash
  namespace: nautible-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nautible-app-payment-cash
        image: nautible-app-payment-cash
        env:
        - name: QUARKUS_PROFILE
          value: local-dev
