---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-payment-credit
  namespace: nautible-app-ms
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nautible-app-ms-payment-credit
        image: nautible-app-ms-payment-credit
        env:
        - name: LOG_LEVEL # DEBUG, INFO, WARN, ERROR, DPANIC, PANIC, FATAL
          value: DEBUG
        - name: LOG_FORMAT # json, console
          value: console
        - name: DYNAMODB_REGION
          value: ap-northeast-1
        - name: DYNAMODB_ENDPOINT
          value: http://payment-localstack.nautible-app-ms.svc.cluster.local:4566
        - name: AWS_ACCESS_KEY
          value: test-key
        - name: AWS_SECRET_KEY
          value: test-secret
