---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-payment
  namespace: nautible-app-ms
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nautible-app-ms-payment
        image: nautible-app-ms-payment
        env:
        - name: DB_HOST
          value: payment-mongodb
        - name: DB_PORT
          value: "27017"
        - name: DB_USER
          value: root
        - name: DB_PW
          value: password
        lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "sleep 30"