---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-payment
  namespace: nautible-app-ms
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nautible-app-ms-payment
        image: nautible-app-ms-payment
        env:
        - name: DB_CONNECTION_STRING
          value: mongodb://${DB_USER}:${DB_PW}@payment-mongodb:27017/Payment?authSource=admin
        - name: DB_USER
          value: root
        - name: DB_PW
          value: password
        lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "for i in `seq 1 10`; do curl -I -m 2 http://payment-redis:6379/ -o /dev/null || if [ $? == 8 ];then break; else true;fi; sleep 5; done"
                - "for i in `seq 1 60`; do curl http://payment-mongodb:8081/ >/dev/null && break || true; sleep 5; done"
