apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-payment-credit
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-payment-credit
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-ms-cosmosdb
              key: DATABASE_USER
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-ms-cosmosdb
              key: DATABASE_PW
