apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-payment-credit
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-payment-credit
        env:
        - name: LOG_LEVEL # DEBUG, INFO, WARN, ERROR, DPANIC, PANIC, FATAL
          value: INFO
        - name: LOG_FORMAT # json, console
          value: console
        - name: DYNAMODB_REGION
          value: ap-northeast-1
