apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-payment
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-payment
        image: nautible-app-ms-payment
        env:
        - name: DB_HOST
          value: mongo.cosmos.azure.com
        - name: DB_PORT
          value: "10255"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-ms-cosmosdb
              key: DATABASE_USER
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-ms-cosmosdb
              key: DATABASE_PW
