---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-localstack
  namespace: nautible-app-ms
  labels:
    app.kubernetes.io/name: payment-localstack
    app.kubernetes.io/instance: payment-localstack
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: localstack
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: payment-localstack
      app.kubernetes.io/component: localstack
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payment-localstack
        app.kubernetes.io/instance: payment-localstack
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: localstack
        app.kubernetes.io/part-of: nautible
        app.kubernetes.io/managed-by: manual
    spec:
      containers:
        - name: payment-localstack
          image: localstack/localstack:0.14.1
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: dynamodb,sqs,sns
            - name: START_WEB
              value: "0"
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  # create profile and dynamo table and item
                  - "mkdir ~/.aws \
                    && echo \"[profile localstack]\" >> ~/.aws/config \
                    && echo \"region = ap-northeast-1\" >> ~/.aws/config \
                    && echo \"output = json\" >> ~/.aws/config \
                    && echo \"[localstack]\" >> ~/.aws/credentials \
                    && echo \"aws_access_key_id = test-key\" >> ~/.aws/credentials \
                    && echo \"aws_secret_access_key = test-secret\" >> ~/.aws/credentials \
                    && aws dynamodb create-table --table-name Payment --attribute-definitions AttributeName=OrderNo,AttributeType=S --key-schema AttributeName=OrderNo,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --profile localstack --endpoint-url=http://localhost:4566 \
                    && aws dynamodb create-table --table-name PaymentHistory --attribute-definitions AttributeName=RequestId,AttributeType=S --key-schema AttributeName=RequestId,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --profile localstack --endpoint-url=http://localhost:4566 \
                    && aws dynamodb create-table --table-name Sequence --attribute-definitions AttributeName=Name,AttributeType=S --key-schema AttributeName=Name,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --profile localstack --endpoint-url=http://localhost:4566 \
                    && aws dynamodb put-item --table-name=Sequence --item '{\"Name\": {\"S\": \"Payment\"}, \"SequenceNumber\": {\"N\": \"0\"}}' --profile localstack --endpoint-url=http://localhost:4566"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-localstack
  namespace: nautible-app-ms
  labels:
    app.kubernetes.io/name: payment-localstack
    app.kubernetes.io/instance: payment-localstack
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: localstack
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  selector:
    app.kubernetes.io/instance: payment-localstack
    app.kubernetes.io/component: localstack
  ports:
    - name: payment-localstack
      port: 4566
