apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-payment-credit
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-payment-credit
        env:
      - name: DYNAMODB_REGION
        value: ap-northeast-1
