apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-payment
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-payment
        image: nautibledevacr.azurecr.io/nautible-app-ms-payment:27a1b0255770b4ec9b3255fd23f56636b140908d
        env:
        - name: LOG_LEVEL # DEBUG, INFO, WARN, ERROR, DPANIC, PANIC, FATAL
          value: INFO
        - name: LOG_FORMAT # json, console
          value: json
        - name: DB_CONNECTION_STRING
          value: mongodb://${DB_USER}:${DB_PW}@${DB_USER}.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@${DB_USER}@
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-ms-cosmosdb
              key: DATABASE_USER
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-ms-cosmosdb
              key: DATABASE_PW
